### ISSUE TITLE
build prototype laptop picture holder

### ISSUE THREAD

**Issue by silky** [hahayes/hahayes-projects#14]
suppose i were to have a laptop-sized plastic pocket-esque thing. attached to the front of my laptop Then it would be possible to place a piece of appropriately-sized paper into it.

i think it would be pretty easy to make such a thing; even though existing plastic pockets wouldn't be the write size.

(i.e. just get two pieces of a3-sized hard-ish plastic, cut to appropriate size; staple them together.

this is genius.

**Comment by silky** [comment]
it could even be bordered perhaps by black masking tape ...

**Comment by silky** [comment]
infact of course the back could just be regular thin cardboard or something; whatever, just the front needs to be nice clear solid plastic.

**Comment by silky** [comment]
first prototype:

![laptop-art-holder-1](https://cloud.githubusercontent.com/assets/129525/3868279/0f3f7a68-2032-11e4-8bc6-2ed62cf1a351.JPG)

material:
- single sheet of an a3 plastic pocket cut to size,
- front of a3 graph paper used as backing,
- white masking tape to stick it together.

lessons learned:
- cutting straight is hard; need a craft knife or one of those cutting tables,
- masking tape isn't a great choice unless it's black and all the same - i just used what i had available,
- a thicker a3 plastic see-through folder wasn't appropriate because it had a button right in the middle where i needed it to be clear.
- i think a nice border might be a good idea, hence again the black masking tape should be applied appropriately, not haphazzardly.
- also; the border shouldn't be too thick.

summary:
- this works. v1 is bad, but i'll try and build v2 later on with black masking tape and it should be fine.

**Comment by silky** [comment]
second version:

![laptop-art-holder-2](https://cloud.githubusercontent.com/assets/129525/3868491/4d97ddfe-2047-11e4-82ae-39a070f0a4d4.JPG)

actually i just removed the masking tape from the first one.

this looks much nicer i think. i still can't actually find velcro dots; but as soon as i do i can attach it to my laptop. i think this is done now. the only thing missing might be a seal at the top. but i'm quite happy. it might be possible to sell these at an art stand.

anyway, i'm considering this issue closed!

**Comment by silky** [comment]
finally attached to laptop:

![laptop-art-holder-4](https://cloud.githubusercontent.com/assets/129525/3868873/eb23f152-206a-11e4-8020-c51f704c4419.JPG)

http://silky.github.io/posts/2014-08-10-laptop-art-holder.html

**Comment by mobeets** [comment]
this is cool. imagine changing the image depending on what you're working on; sorta like when people are reading a book you can see their book cover to know what it is.

also, i just found your "on me" post and really enjoyed reading it. so weird how many things people keep on themselves, and where they put it. e.g. you: you have so much in your right pocket, and then only a handkerchief in your left! crazy.

**Comment by silky** [comment]
yes; i like the idea of changing it based what i'm working on.

though i guess the whiteboard could also be used for that.

i like this because it can contain things that i can't draw. though yeah, a set of different images representing things might be quite fun. i also like that it's totally interchangable with the laptop whiteboard.

**Comment by silky** [comment]
it occurs to me this could be used to play a stupid prank on people: slightly change the picture every so often. for exmaple, if it's a picture of a person, have them change the direction that look.

but it's going to be hard to pull off changing it without the target noticing.
