### ISSUE TITLE
create a set of imagines that can be composed together to form unique scenes

### ISSUE THREAD

**Issue by silky** [hahayes/hahayes-projects#19]
for example, generate the attached by maybe 50 layered images

![006](https://cloud.githubusercontent.com/assets/129525/3947142/22621f9e-2684-11e4-9f9f-141222b837ee.jpeg)

alternatively, add more wavey lines to a picture like this:
![ylxdxzv](https://cloud.githubusercontent.com/assets/129525/3947146/541d2614-2684-11e4-9413-0ad09cbe3af0.jpg)

or something.

then, once we had this we could:
- use it as an email reader. when a new email comes in, it could add (or remove) a scene. then you'd get an artistic representation of the number of emails you have.
  - ???

**Comment by mobeets** [comment]
great idea! i love your propensity for making prettier ways of checking your email. (still use voronoi mail?)

although if my inbox looked like that first image, that would only make me want to keep more emails around...

the more fantastic the scene the better--i.e. who cares about gravity? have people floating everywhere.

ooh, also, maybe this thing could use groups of objects to represent groups of email by their label. so you have 5 people seated in a circle to represent your 5 work emails, for example.
- spam emails, subscription-type emails: more decorative scene elements, e.g. flowers, totems, etc.
- work emails: structural scene elements, e.g. buildings, chairs
- friend/personal emails: people

**Comment by mobeets** [comment]
i forgot to begin that comment with how much i love that first image.

also, i was just noticing how the scene depth adds a lot of interest to it--it'd be way less pretty i think without its layers.

what if you scaled the image tokens by the age of the email! so the depth in the scene signals how old the emails in your inbox are.

**Comment by silky** [comment]
yes - i love the idea of incorporating spots in the scene for particular types of things. that is absoulte genius. it wouldn't be hard to do either, if we decided it would support at most say 5 emails from each group at once, or something. infact, i _really_ like this idea.

have people that could be placed in particular scenes. change out the background 'setting' and just incorporate new people of the right size in the appropriate location.

yeah man, that imagine is the featured art in laptop art holder - http://silky.github.io/posts/2014-08-14-featured-artist-pablo-amaringo.html - the guy has heaps of similar stuff that is all awesome!

(and no, for one reason or another i'm not using voronoi mail; i think partly because i couldn't get it to work on linux. i might try again, though ...; it was a brilliant idea.)

**Comment by silky** [comment]
i guess there are a few ways to proceed:
- select a list of cool landscapes (or generate them?) and mark out regions where we could place images of people.

the downside is that in order to get an image like the first one a ridiculous amount of artistic effort is required...
- alternatively, we could generate more abstract scenes, and then just "add" to them, similarly-abstractly. this is perhaps less interesting but easier.
- i guess on the other hand, i wouldn't even mind if we just took a set of the pablo amaringo images, and then photoshop'd out some elements (the ufo's or people or whatever) and then just placed them back into the image as emails come in

**Comment by mobeets** [comment]
yes to all things. maybe along the lines of photoshopping, we could establish categories of things we need and just start compiling examples:
- backgrounds (plainish, with depth, e.g. caves, forests, but whatever really as long as it's big)
- people, animals, inanimate objects

so we could start by photoshopping out the animals and things in the amaringo ones, but keep going as we find other images. 

and then maybe each image snippet is attached to certain themes, e.g. "amaringo", or maybe it's just a free-for-all and the collages we get are just a mix of strange creatures. then we just have to be able to scale them up and down in a nice way.

**Comment by silky** [comment]
agreed; that sounds like a good way to proceed.

i've created a repo for this - https://github.com/hahayes/scene-composary - let's gather up images and chuck them in there, and we can make more discrete tasks over there when appropriate.

**Comment by silky** [comment]
fwiw in the spirit of ridiculous things that notify you of incoming emails; we could adopt this exact same idea with music. it seems perhaps more fun to do it in reverse though - have a song playing with say 10 instruments, and you have 0 unread emails. now for each incoming email, an instrument is removed.

-- edit: most annoying extension of this idea - just write a program that says "email" once, for every email you have that isn't read, every minute (say).

this would be insanely annoying. but maybe it's similar in mental time-wastingness as having the number of unread emails present in the tab that you can constantly see.

**Comment by mobeets** [comment]
hahaha oh man, i love this idea. and we could tell users that they're downloading some much cooler email notification thing, but then it turns out to be the guy just saying "email," and they can never uninstall it.

**Comment by silky** [comment]
make it a firefox plugin.

thanks for reminding me about voronoi email by the way; i'm using it again now! it's great! - https://github.com/silky/voronoi-mail - i changed it so that you specify the password in the "keyring" thing, instead of over the website, which is more relaxing. because it means i don't need to retype the password everytime i close the browser, or something.

**Comment by silky** [comment]
fwiw, i implemented that "email" wav thing in voronoi email. 

it's as ridiculous as you'd imagine.

**Comment by mobeets** [comment]
the wave thing meaning that second  photo? post a photo!

**Comment by mobeets** [comment]
oh i see, you mean the sound! haha that's great
