### ISSUE TITLE
attempt spraypaint version of logo, using stencil

### ISSUE THREAD

**Issue by silky** [hahayes/hahayes-projects#5]
on paper, with masking tape where the text is?

**Comment by silky** [comment]
i probably need to purchase some a3 paper for this. or infact maybe a big a3 book of paper. because that'd be fun to have.

**Comment by mobeets** [comment]
that sounds like fun! definitely post photos of any attempts

**Comment by silky** [comment]
here's my attempt with:
- a3 graph paper,
- masking tape for the lettering,
- a bunch of bright spraypaint that i had.

i learned that:
- masking tape is bad for creating round lettering. especially if you're impatient. 
- graph paper isn't ideal if you want it to be white,
- the spray painting worked out not too badly, but could probably use another coat to completely hide the paper.

i think next time i'll try stencils - i.e. cut out the letters from cardboard, then stick them on and paint around them.

![logo-2](https://cloud.githubusercontent.com/assets/129525/3868126/69fe9be0-2024-11e4-83cd-cfce9210fb3e.JPG)
![logo-3](https://cloud.githubusercontent.com/assets/129525/3868125/69fe2994-2024-11e4-9ff9-b5eed6ac46ff.JPG)
![logo-4](https://cloud.githubusercontent.com/assets/129525/3868129/6a095d0a-2024-11e4-9795-7aacfc855ce0.JPG)
![logo-5](https://cloud.githubusercontent.com/assets/129525/3868128/6a084988-2024-11e4-8b61-8add2d3d38ad.JPG)
![logo-6](https://cloud.githubusercontent.com/assets/129525/3868127/6a032584-2024-11e4-9819-00e47076c8e9.JPG)
![logo-7](https://cloud.githubusercontent.com/assets/129525/3868131/6a26359c-2024-11e4-9954-2566fa2d1477.JPG)
![logo-8](https://cloud.githubusercontent.com/assets/129525/3868130/6a25a3b6-2024-11e4-9049-cafc70ac0aec.JPG)

**Comment by mobeets** [comment]
that looks awesome! good colors

**Comment by silky** [comment]
thanks! yeah i'm happy with how the colours turned out; though something a bit odd happened with the yellow (kind of cemented itself in that area).

**Comment by silky** [comment]
this is completed actually!
