### ISSUE TITLE
clojure stoner rock band using overtone

### ISSUE THREAD

**Issue by silky** [hahayes/hahayes-projects#6]
see http://overtone.github.io/

and http://meta-ex.com/ for the coolest people ever.

**Comment by silky** [comment]
i'm thinking of music simlar to tame impala, king gizard and the lizzard wizzard, black rebel motorcycle club, and all those similar bands.

**Comment by silky** [comment]
there are some very simple questions i don't know the answer to, for example:
1. how to make drum sounds?
2. how to make guitar sounds?
3. how to make distorted guitar sounds?

etc.

not to mention, how to even do anything in clojure at all. do we need to learn emacs? how do you record things? can i save sessions and come back? etc etc.

**Comment by mobeets** [comment]
this is so cool! i made a [gist](https://gist.github.com/mobeets/e9f261b1246643592c52) for getting started--not that it was difficult, but to minimize number of tabs needed

**Comment by silky** [comment]
sweet! i tried to get it working just now, but i might need to upgrade my linux or something; so i think i'll do that a little bit later ... would love to hear what you make!

**Comment by mobeets** [comment]
this is so much fun! once you get it set up: [live coding](https://github.com/overtone/overtone/wiki/Live-coding). definitely worth it!

**Comment by silky** [comment]
turns out there's a community around this - http://toplap.org/

**Comment by mobeets** [comment]
good find! i haven't gotten far at all yet, but i am very excited.

**Comment by silky** [comment]
yeah; i'm still trying to upgrade my computer. ubuntu decided to drop all the package archives for the version i was using - 13.04 - which i think is a very odd move.

**Comment by mobeets** [comment]
hahaha, i love how you say that as if you're trying not to offend ubuntu by questioning its motives

**Comment by silky** [comment]
woohoo so i finally got this working thanks for this faq - http://jackaudio.org/faq/pulseaudio_and_jack.html - option number 4 worked brilliantly.

**Comment by silky** [comment]
moved here - https://github.com/hahayes/psychadelic-sounds/issues
